### ISSUE TITLE
"IndexError: list index out of range" for run example when adding -i -t to ARGS_ALWAYS

### ISSUE THREAD

**Issue by saviola777** [joernhees/userdocker#4]
I uncommented the lines for `-i` and `-t` in the config file, like this:

```
ARGS_ALWAYS = {
    'run': [
        '-t',
        '-i',
        '--rm',
    ],
}
```

When now running `sudo userdocker run -v $HOME:$HOME debian bash`, I get the following error:

```
Traceback (most recent call last):
  File "/usr/bin/userdocker", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/userdocker/userdocker.py", line 42, in main
    parse_and_exec_cmd()
  File "/usr/lib/python3.6/site-packages/userdocker/userdocker.py", line 35, in parse_and_exec_cmd
    args = parse_args()
  File "/usr/lib/python3.6/site-packages/userdocker/parser.py", line 72, in parse_args
    specific_parser(subparsers)
  File "/usr/lib/python3.6/site-packages/userdocker/subcommands/run.py", line 37, in parser_run
    sub_parser = init_subcommand_parser(parser, 'run')
  File "/usr/lib/python3.6/site-packages/userdocker/helpers/parser.py", line 51, in init_subcommand_parser
    "const": args[0],
IndexError: list index out of range
```

**Comment by joernhees** [comment]
yupp, i had initially expected people to decide between ALWAYS and AVAILABLE...

**Comment by saviola777** [comment]
Ah yeah, sorry, missed that part.
